//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.WebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string HLP_WebService_2_0_Homologacao_NFeRecepcao_RS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_2_0_Homologacao_NFeRecepcao_RS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx")]
        public string HLP_WebService_2_0_Homologacao_NFe_RetRecepacao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_2_0_Homologacao_NFe_RetRecepacao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx")]
        public string HLP_WebService_2_0_Homologacao_NFeCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_2_0_Homologacao_NFeCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string HLP_WebService_2_0_Homologacao_NFeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_2_0_Homologacao_NFeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string HLP_WebService_2_0_Homologacao_NFeConsulta_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_2_0_Homologacao_NFeConsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asm" +
            "x")]
        public string HLP_WebService_2_0_Homologacao_NFeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_2_0_Homologacao_NFeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string HLP_WebService_v2_Producao_NFeRecepcao_RS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRecepcao_RS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx")]
        public string HLP_WebService_v2_Producao_NFeRetRecepcao_RS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRetRecepcao_RS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx")]
        public string HLP_WebService_v2_Producao_NFeCancelamento_RS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeCancelamento_RS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string HLP_WebService_v2_Producao_NFeInutilizacao_RS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeInutilizacao_RS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string HLP_WebService_v2_Producao_NFeConsulta_RS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeConsulta_RS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string HLP_WebService_v2_Producao_NFeStatusServico_RS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeStatusServico_RS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sef.sefaz.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx")]
        public string HLP_WebService_v2_Producao_NFeConsultaCadastro_RS_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeConsultaCadastro_RS_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nferecepcao2.asmx")]
        public string HLP_WebService_v2_Producao_NFeRecepcao_SP_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRecepcao_SP_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nferetrecepcao2.asmx")]
        public string HLP_WebService_v2_Producao_NFeRetRecepcao_SP_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRetRecepcao_SP_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfecancelamento2.asmx")]
        public string HLP_WebService_v2_Producao_NFeCancelamento_SP_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeCancelamento_SP_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeinutilizacao2.asmx")]
        public string HLP_WebService_v2_Producao_NFeInutilizacao_SP_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeInutilizacao_SP_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeconsulta2.asmx")]
        public string HLP_WebService_v2_Producao_NFeConsulta_SP_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeConsulta_SP_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfestatusservico2.asmx")]
        public string HLP_WebService_v2_Producao_NFeStatusServico_SP_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeStatusServico_SP_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/cadconsultacadastro2.asmx")]
        public string HLP_WebService_v2_Producao_NFeConsulta_SP1_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeConsulta_SP1_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRetRecepcao2")]
        public string HLP_WebService_v2_Homologacao_RetRecepcao_MS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_RetRecepcao_MS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRecepcao2")]
        public string HLP_WebService_v2Homologacao_NFeRecepcao_MS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2Homologacao_NFeRecepcao_MS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeCancelamento2")]
        public string HLP_WebService_v2Homologacao_NFeCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2Homologacao_NFeCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeInutilizacao2")]
        public string HLP_WebService_v2_Homologacao_NFeInutilizacao_MS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeInutilizacao_MS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeConsulta2")]
        public string HLP_WebService_v2_Homologacao_NFeConsulta_MS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeConsulta_MS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2")]
        public string HLP_WebService_v2_Homologacao_NFeStatusServico_MS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeStatusServico_MS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/CadConsultaCadastro2")]
        public string HLP_WebService_v2_Homologacao_NFeCadConsultaCadastro_MS_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeCadConsultaCadastro_MS_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_WebService_v2_SCAN_NFeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_NFeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_WebService_v2_SCAN_Producao_NFeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Producao_NFeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string HLP_WebService_v2_SCAN_Producao_NFeCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Producao_NFeCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string HLP_WebService_v2_SCAN_Producao_NFeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Producao_NFeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_WebService_v2_SCAN_Producao_NFeConsulta_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Producao_NFeConsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NFeStatusServico2/NFeStatusServico2.asmx")]
        public string HLP_WebService_v2_SCAN_Producao_NFeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Producao_NFeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_WebService_v2_SCAN_Homologacao_NFeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Homologacao_NFeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_WebService_v2_SCAN_Homologacao_NFeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Homologacao_NFeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string HLP_WebService_v2_SCAN_Producao_NFeCancelamento1_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Producao_NFeCancelamento1_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string HLP_WebService_v2_SCAN_Homologacao_NFeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Homologacao_NFeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_WebService_v2_SCAN_Homologacao_NFeConsulta_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Homologacao_NFeConsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string HLP_WebService_v2_SCAN_Homologacao_NFeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_SCAN_Homologacao_NFeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRecepcao2.asmx")]
        public string HLP_WebService_v2_Homologacao_NFeRecepcao_SP_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeRecepcao_SP_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRetRecepcao2.asmx")]
        public string HLP_WebService_v2_Producao_NfeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NfeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeStatusServico2.asmx")]
        public string HLP_WebService_v2_Homologacao_NFeStatusServico_SP_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeStatusServico_SP_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeCancelamento2.asmx")]
        public string HLP_WebService_v2_Homologacao_NFeCancelamento_SP_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeCancelamento_SP_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeInutilizacao2.asmx")]
        public string HLP_WebService_v2_Homologacao_NFeInutilizacao_SP_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeInutilizacao_SP_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeConsulta2.asmx")]
        public string HLP_WebService_v2_Homologacao_NFeConsulta_SP_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeConsulta_SP_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeWEB/services/cadconsultacadastro.asm" +
            "x")]
        public string HLP_WebService_v2_Homologacao_NFeCadConsultaCadastro_SP_CadConsultaCadastro {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeCadConsultaCadastro_SP_CadConsultaCadastro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeRecepcao2")]
        public string HLP_WebService_v2_Producao_NFeRecepcao_MS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRecepcao_MS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeRetRecepcao2")]
        public string HLP_WebService_v2_Producao_NFeRetRecepcao_MS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRetRecepcao_MS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeCancelamento2")]
        public string HLP_WebService_v2_Producao_NFeCancelamento_MS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeCancelamento_MS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeInutilizacao2")]
        public string HLP_WebService_v2_Producao_NFeInutilizacao_MS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeInutilizacao_MS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeConsulta2")]
        public string HLP_WebService_v2_Producao_NFeConsuta_MS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeConsuta_MS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeStatusServico2")]
        public string HLP_WebService_v2_Producao_NFeStatusServico_MS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeStatusServico_MS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/CadConsultaCadastro2")]
        public string HLP_WebService_v2_Producao_NFeConsultaCadastro_MS_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeConsultaCadastro_MS_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.ginfes.com.br//ServiceGinfesImpl")]
        public string HLP_WebService_Itu_servicos_Producao_ServiceGinfesImplService {
            get {
                return ((string)(this["HLP_WebService_Itu_servicos_Producao_ServiceGinfesImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.ginfes.com.br//ServiceGinfesImpl")]
        public string HLP_WebService_Itu_servicos_Homologacao_ServiceGinfesImplService {
            get {
                return ((string)(this["HLP_WebService_Itu_servicos_Homologacao_ServiceGinfesImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx" +
            "")]
        public string HLP_WebService_v2_Homologacao_NFeRecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_NFeRecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string HLP_WebService_v2_Homologacao_RecepcaoEvento_RS_RecepcaoEvento {
            get {
                return ((string)(this["HLP_WebService_v2_Homologacao_RecepcaoEvento_RS_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string HLP_WebService_v2_Producao_NFeRecepcaoEvento_RS_RecepcaoEvento {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRecepcaoEvento_RS_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/RecepcaoEvento")]
        public string HLP_WebService_v2_Producao_NFeRecepcaoEvento_MS_NfeRecepcaoEvento {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRecepcaoEvento_MS_NfeRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx")]
        public string HLP_WebService_v2_Producao_NFeRecepacaoEvento_SP_RecepcaoEvento {
            get {
                return ((string)(this["HLP_WebService_v2_Producao_NFeRecepacaoEvento_SP_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.75.170.94/Versionamento/Verisionamento.asmx")]
        public string HLP_WebService_Ws_versionamento_Cliente_Verisionamento {
            get {
                return ((string)(this["HLP_WebService_Ws_versionamento_Cliente_Verisionamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx")]
        public string HLP_WebService_Homologacao_cteRecepcao_CteRecepcao {
            get {
                return ((string)(this["HLP_WebService_Homologacao_cteRecepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx")]
        public string HLP_WebService_CTe_Homologacao_cteRetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["HLP_WebService_CTe_Homologacao_cteRetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteCancelamento.asmx")]
        public string HLP_WebService_CTe_Homologacao_cteCancelamento_CteCancelamento {
            get {
                return ((string)(this["HLP_WebService_CTe_Homologacao_cteCancelamento_CteCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx")]
        public string HLP_WebService_CTe_Homologacao_cteConsulta_CteConsulta {
            get {
                return ((string)(this["HLP_WebService_CTe_Homologacao_cteConsulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx")]
        public string HLP_WebService_CTe_Homologacao_cteInutilizacao_CteInutilizacao {
            get {
                return ((string)(this["HLP_WebService_CTe_Homologacao_cteInutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx")]
        public string HLP_WebService_CTe_Homologacao_cteStatusServico_CteStatusServico {
            get {
                return ((string)(this["HLP_WebService_CTe_Homologacao_cteStatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx")]
        public string HLP_WebService_CTe_Producao_cteRecepcao_CteRecepcao {
            get {
                return ((string)(this["HLP_WebService_CTe_Producao_cteRecepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx")]
        public string HLP_WebService_CTe_Producao_cteRetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["HLP_WebService_CTe_Producao_cteRetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx")]
        public string HLP_WebService_CTe_Producao_cteStatusServico_CteStatusServico {
            get {
                return ((string)(this["HLP_WebService_CTe_Producao_cteStatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteCancelamento.asmx")]
        public string HLP_WebService_CTe_Producao_cteCancelamento_CteCancelamento {
            get {
                return ((string)(this["HLP_WebService_CTe_Producao_cteCancelamento_CteCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx")]
        public string HLP_WebService_CTe_Producao_cteInutilizacao_CteInutilizacao {
            get {
                return ((string)(this["HLP_WebService_CTe_Producao_cteInutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx")]
        public string HLP_WebService_CTe_Producao_cteConsulta_CteConsulta {
            get {
                return ((string)(this["HLP_WebService_CTe_Producao_cteConsulta_CteConsulta"]));
            }
        }
    }
}
